app:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/ApiResource/Controller/
        namespace: Api\Controller
    type: attribute